apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: database
  namespace: flux-system
spec:
  interval: 5m
  path: ./apps/base/postgres-cluster
  prune: true
  dependsOn:
    - name: monitoring
  sourceRef:
    kind: GitRepository
    name: gitops-v1
  timeout: 3m
