apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: cnpg-operator
  namespace: flux-system
spec:
  interval: 10m
  path: ../../apps/base/cloudnativepg
  prune: true
  sourceRef:
    kind: GitRepository
    name: gitops-v1

---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: postgres-cluster
  namespace: flux-system
spec:
  interval: 10m
  path: ../../apps/base/postgres-cluster
  prune: true
  sourceRef:
    kind: GitRepository
    name: gitops-v1
  dependsOn:
    - name: cnpg-operator

---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: monitoring
  namespace: flux-system
spec:
  interval: 10m
  path: ../../apps/base/monitoring
  prune: true
  sourceRef:
    kind: GitRepository
    name: gitops-v1
