apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: monitoring
  namespace: flux-system
spec:
  interval: 5m
  path: ./apps/base/monitoring
  prune: true
  sourceRef:
    kind: GitRepository
    name: gitops-v1
  timeout: 3m
