apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cloudnativepg
  namespace: cnpg-system
spec:
  interval: 5m
  chart:
    spec:
      chart: cloudnative-pg
      version: "0.25.0"
      sourceRef:
        kind: HelmRepository
        name: cloudnativepg
        namespace: flux-system
  install:
    createNamespace: true
    crds: Create
  upgrade:
    crds: Create
  values:
    monitoring:
      podMonitorEnabled: true
